### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by agustincards14** [EddyGonzalez/343TermProject#1]
WE NEED TO DO THIS NOW

Edit: So  much for "NOW"

**Comment by alopezz217** [comment]
[Project Plan Example.pdf](https://github.com/EddyGonzalez/343TermProject/files/800748/Project.Plan.Example.pdf)

**Comment by EddyGonzalez** [comment]
Sick

**Comment by alopezz217** [comment]
[https://docs.google.com/document/d/1Mizhxe_TeolOrsw0y1M7XYSuuIlEo29lRmC45yeReRw/edit](url)

**Comment by alopezz217** [comment]
[https://docs.google.com/document/d/1Mizhxe_TeolOrsw0y1M7XYSuuIlEo29lRmC45yeReRw/edit?usp=sharing](url)
